name = "hono-rwa-myaccount"
main = "src/index.ts"
compatibility_date = "2025-11-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
preview_urls = true

[build]
    command = "pnpm run build"

[observability]
enabled = true
head_sampling_rate = 1

